- import_tasks: "{{ role_path }}/tasks/init.yml"
  tags:
    - always

- import_tasks: "{{ role_path }}/tasks/validate_config.yml"
  when: "run_setup|bool and matrix_postgres_enabled|bool"
  tags:
    - setup-all
    - setup-postgres

- import_tasks: "{{ role_path }}/tasks/setup_postgres.yml"
  when: run_setup|bool
  tags:
    - setup-all
    - setup-postgres

- import_tasks: "{{ role_path }}/tasks/import_postgres.yml"
  when: run_postgres_import|bool
  tags:
    - import-postgres

- import_tasks: "{{ role_path }}/tasks/import_sqlite_db.yml"
  when: run_postgres_import_sqlite_db|bool
  tags:
    - import-sqlite-db

- import_tasks: "{{ role_path }}/tasks/upgrade_postgres.yml"
  when: run_postgres_upgrade|bool
  tags:
    - upgrade-postgres

- import_tasks: "{{ role_path }}/tasks/run_synapse_janitor.yml"
  when: run_postgres_synapse_janitor|bool
  tags:
    - run-postgres-synapse-janitor

- import_tasks: "{{ role_path }}/tasks/run_vacuum.yml"
  when: run_postgres_vacuum|bool
  tags:
    - run-postgres-vacuum
