- import_tasks: "{{ role_path }}/tasks/init.yml"
  tags:
    - always

- import_tasks: "{{ role_path }}/tasks/validate_config.yml"
  when: run_setup|bool
  tags:
    - setup-all
    - setup-synapse

- import_tasks: "{{ role_path }}/tasks/setup_synapse.yml"
  when: run_setup|bool
  tags:
    - setup-all
    - setup-synapse

- import_tasks: "{{ role_path }}/tasks/import_media_store.yml"
  when: run_synapse_import_media_store|bool
  tags:
    - import-media-store

- import_tasks: "{{ role_path }}/tasks/register_user.yml"
  when: run_synapse_register_user|bool
  tags:
    - register-user

- import_tasks: "{{ role_path }}/tasks/self_check_client_api.yml"
  delegate_to: 127.0.0.1
  become: false
  when: run_self_check|bool
  tags:
    - self-check

- import_tasks: "{{ role_path }}/tasks/self_check_federation_api.yml"
  delegate_to: 127.0.0.1
  become: false
  when: run_self_check|bool
  tags:
    - self-check

- import_tasks: "{{ role_path }}/tasks/update_user_password.yml"
  when: run_synapse_update_user_password|bool
  tags:
    - update-user-password

- name: Mark matrix-synapse role as executed
  set_fact:
    matrix_synapse_role_executed: true
  tags:
   - always
