---

# If the matrix-synapse role is not used, `matrix_synapse_role_executed` won't exist.
# We don't want to fail in such cases.
- name: Fail if matrix-synapse role already executed
  fail:
    msg: >-
      The matrix-bridge-mautrix-hangouts role needs to execute before the matrix-synapse role.
  when: "matrix_synapse_role_executed|default(False)"

- name: Ensure Mautrix Hangouts image is pulled
  docker_image:
    name: "{{ matrix_mautrix_hangouts_docker_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ matrix_mautrix_hangouts_docker_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else matrix_mautrix_hangouts_docker_image_force_pull }}"

- name: Ensure Mautrix Hangouts paths exist
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_username }}"
  with_items:
    - "{{ matrix_mautrix_hangouts_base_path }}"
    - "{{ matrix_mautrix_hangouts_config_path }}"
    - "{{ matrix_mautrix_hangouts_data_path }}"

- name: Check if an old database file already exists
  stat:
    path: "{{ matrix_mautrix_hangouts_base_path }}/mautrix-hangouts.db"
  register: matrix_mautrix_hangouts_stat_database

- name: (Data relocation) Ensure matrix-mautrix-hangouts.service is stopped
  service:
    name: matrix-mautrix-hangouts
    state: stopped
    daemon_reload: yes
  failed_when: false
  when: "matrix_mautrix_hangouts_stat_database.stat.exists"

- name: (Data relocation) Move mautrix-hangouts database file to ./data directory
  command: "mv {{ matrix_mautrix_hangouts_base_path }}/mautrix-hangouts.db {{ matrix_mautrix_hangouts_data_path }}/mautrix-hangouts.db"
  when: "matrix_mautrix_hangouts_stat_database.stat.exists"

- name: Ensure mautrix-hangouts config.yaml installed
  copy:
    content: "{{ matrix_mautrix_hangouts_configuration|to_nice_yaml }}"
    dest: "{{ matrix_mautrix_hangouts_config_path }}/config.yaml"
    mode: 0644
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_username }}"

- name: Ensure mautrix-hangouts registration.yaml installed
  copy:
    content: "{{ matrix_mautrix_hangouts_registration|to_nice_yaml }}"
    dest: "{{ matrix_mautrix_hangouts_config_path }}/registration.yaml"
    mode: 0644
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_username }}"

- name: Ensure matrix-mautrix-hangouts.service installed
  template:
    src: "{{ role_path }}/templates/systemd/matrix-mautrix-hangouts.service.j2"
    dest: "/etc/systemd/system/matrix-mautrix-hangouts.service"
    mode: 0644
  register: matrix_mautrix_hangouts_systemd_service_result

- name: Ensure systemd reloaded after matrix-mautrix-hangouts.service installation
  service:
    daemon_reload: yes
  when: "matrix_mautrix_hangouts_systemd_service_result.changed"
